// Regenerates src/generated/poses.ts from the published OpenAPI document. Pose
// names come from the `pose` query-parameter enum on POST /v1/render. By default
// the live spec is fetched over HTTP; pass a file path or an http(s) URL to
// override (for testing or offline runs). No spec file is written to disk.
//
//   npx tsx scripts/generate-poses.ts [openapi.json | https://host/v1/openapi.json]

import { readFile, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const DEFAULT_SPEC_URL = "https://api.createrington.com/v1/openapi.json";
const SPEC_URL_ENV = "SKIN_API_OPENAPI_URL";

const here = dirname(fileURLToPath(import.meta.url));
const SDK_ROOT = resolve(here, "..");
const OUT_FILE = join(SDK_ROOT, "src", "generated", "poses.ts");

function resolveSource(argv: string[]): string {
  if (argv[2]) return argv[2];
  const env = process.env[SPEC_URL_ENV];
  if (env) return env;
  return DEFAULT_SPEC_URL;
}

function isHttpUrl(source: string): boolean {
  return /^https?:\/\//i.test(source);
}

async function loadSpec(source: string): Promise<string> {
  if (isHttpUrl(source)) {
    const res = await fetch(source);
    if (!res.ok) {
      throw new Error(`HTTP ${res.status} fetching ${source}`);
    }
    return res.text();
  }
  const path = isAbsolute(source) ? source : resolve(process.cwd(), source);
  return readFile(path, "utf8");
}

interface OpenApiParameter {
  name?: unknown;
  schema?: { enum?: unknown };
}

function poseNames(spec: unknown): string[] {
  if (spec === null || typeof spec !== "object") {
    throw new Error("OpenAPI document is not a JSON object");
  }

  const paths = (spec as { paths?: unknown }).paths;
  const render =
    paths && typeof paths === "object"
      ? (paths as Record<string, unknown>)["/v1/render"]
      : undefined;
  const post =
    render && typeof render === "object"
      ? (render as Record<string, unknown>)["post"]
      : undefined;
  const parameters =
    post && typeof post === "object"
      ? (post as Record<string, unknown>)["parameters"]
      : undefined;

  if (!Array.isArray(parameters)) {
    throw new Error("POST /v1/render parameters is not a list");
  }

  const pose = (parameters as OpenApiParameter[]).find(
    (p) => p && typeof p === "object" && p.name === "pose",
  );
  if (!pose) {
    throw new Error("no 'pose' query parameter found on POST /v1/render");
  }

  const enumValues = pose.schema?.enum;
  if (!Array.isArray(enumValues)) {
    throw new Error("the 'pose' parameter has no enum");
  }

  return enumValues.map((v) => String(v)).sort((a, b) => a.localeCompare(b));
}

async function main(): Promise<void> {
  const source = resolveSource(process.argv);

  let raw: string;
  try {
    raw = await loadSpec(source);
  } catch (err) {
    throw new Error(
      `could not read the OpenAPI document from ${source}: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
  }

  const names = poseNames(JSON.parse(raw) as unknown);
  if (names.length === 0) {
    throw new Error("the pose enum is empty");
  }

  // The names become unquoted keys in the generated `Poses` object, so a name
  // that is not a valid identifier (e.g. "full-body") would emit broken TS.
  const idPattern = /^[A-Za-z_][A-Za-z0-9_]*$/;
  for (const name of names) {
    if (!idPattern.test(name)) {
      throw new Error(
        `pose name "${name}" is not a valid identifier and would break the ` +
          `generated Poses object; update generate-poses.ts to handle it.`,
      );
    }
  }

  const body = `// AUTO-GENERATED by scripts/generate-poses.ts
// Do not edit by hand. Regenerated from the published OpenAPI document.

export const Poses = {
${names.map((p) => `  ${p}: ${JSON.stringify(p)},`).join("\n")}
} as const;

export const KNOWN_POSES = [
${names.map((p) => `  ${JSON.stringify(p)},`).join("\n")}
] as const;

export type KnownPose = (typeof KNOWN_POSES)[number];
`;

  await writeFile(OUT_FILE, body, "utf8");
  process.stdout.write(
    `generated ${OUT_FILE} (${names.length} poses) from ${source}\n`,
  );
}

main().catch((err) => {
  process.stderr.write(`${err instanceof Error ? err.message : String(err)}\n`);
  process.exit(1);
});
